# Generated by Django 5.2.5 on 2025-09-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_user_activation_token_user_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="ViniMRV", max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
    ]
