# Generated by Django 5.2.5 on 2025-09-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_user_username_alter_user_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
