# Generated by Django 5.2.5 on 2025-09-06 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_alter_user_options_alter_user_managers_user_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquizresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserQuiz",
        ),
    ]
