# Generated by Django 5.2.5 on 2025-09-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0007_userquizresult_created_at_delete_userquiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
