version: '3.8'

services:
  backend:
    build: ./backend
    container_name: quiz4fun_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000
